"""ToolLens initial config pool (auto-generated).

Provides per-class config variations for diverse trajectory generation.
"""

from typing import Dict, Any

TOOLLENS_CONFIGS: Dict[str, list] = {}

def get_toollens_configs(class_key: str) -> list:
    return TOOLLENS_CONFIGS.get(class_key, [{}])


# ─── MedicalTools (medical) ──────────
TOOLLENS_CONFIGS["medical"] = [
    {'covid19_cases': [{'country': 'USA', 'date': '2023-01-15', 'cases': 1024, 'deaths': 45}, {'country': 'India', 'date': '2023-02-20', 'cases': 856, 'deaths': 12}, {'country': 'Brazil', 'date': '2023-03-10', 'cases': 432, 'deaths': 8}], 'covid19_lookup_dates': ['2023-01-15', '2023-02-20', '2023-03-10'], 'covid19_lookup_countries': ['USA', 'India', 'Brazil', 'Germany', 'Japan'], 'covid19_empty': [], 'brand_to_generic': {'Tylenol': 'Acetaminophen', 'Advil': 'Ibuprofen', 'Lipitor': 'Atorvastatin', 'Zoloft': 'Sertraline', 'Nexium': 'Esomeprazole', 'Amoxil': 'Amoxicillin', 'Motrin': 'Ibuprofen'}, 'brand_lookup_keys': ['Tylenol', 'Advil', 'Lipitor', 'Zoloft', 'Nexium', 'Amoxil', 'Motrin', 'UnknownBrand'], 'brand_empty': {}, 'tcia_collections': ['LIDC-IDRI', 'TCGA-LUAD', 'PROSTATEx', 'QIN-BREAST', 'REMBRANDT', 'National Lung Screening Trial'], 'tcia_collection_values': ['LIDC-IDRI', 'TCGA-LUAD', 'PROSTATex', 'QIN-BREAST', 'REMBRANDT', 'National Lung Screening Trial'], 'tcia_empty_collections': []},
]

# ─── BusinessTools (business) ──────────
TOOLLENS_CONFIGS["business"] = [
    {'v1_databaseStatus': {'last_updated': '2024-01-15T08:30:00Z', 'status': 'fresh', 'version': '2.1'}, 'All_Exchange_Rates': {'base_currencies': ['USD', 'EUR', 'GBP', 'JPY'], 'rates': {'USD': {'EUR': 0.92, 'GBP': 0.79, 'JPY': 149.5, 'NGN': 1480}, 'EUR': {'USD': 1.09, 'GBP': 0.86}}, 'last_refresh': '2024-01-20T12:00:00Z'}, 'Business_name': {'generated_names': ['Quantum Dynamics LLC', 'Stellar Ventures Inc', 'Nimbus Solutions Ltd']}, 'Businessplan': {'plans': [{'idea': 'SaaS platform', 'plan': 'Executive Summary...'}]}, 'Casino_Tournaments_List': {'tournaments': [{'id': 't1', 'name': 'Weekend Slots Championship', 'prize': 5000, 'status': 'active'}, {'id': 't2', 'name': 'Poker Masters', 'prize': 10000, 'status': 'upcoming'}]}, 'Categorize_Job_Title': {'categories': ['Engineering', 'Sales', 'Marketing', 'Finance', 'Operations'], 'results': {'Software Engineer': 'Engineering', 'Account Executive': 'Sales', 'CFO': 'Finance'}}, 'Fetch_email_of_a_person': {'persons': [{'name': 'John Doe', 'company': 'acme.com', 'email': 'john@acme.com'}, {'name': 'Jane Smith', 'company': 'globex.com'}]}, 'Get_All_Companies_Paginated': {'companies': [{'id': 'RC1234567', 'name': 'Dangote Industries', 'country': 'Nigeria'}, {'id': 'RC2345678', 'name': 'Flutterwave', 'country': 'Nigeria'}], 'page': 1, 'total': 2}, 'Get_a_random_self_help_quote': {'quotes': [{'text': 'The only way to do great work is to love what you do', 'author': 'Steve Jobs', 'tags': ['passion', 'work'], 'book': 'Stanford Speech'}]}, 'Get_all_available_tags_for_self_help_quotes': {'tags': ['motivation', 'success', 'productivity', 'mindfulness', 'leadership', 'habits']}, 'Get_rentals': {'rentals': [{'id': 'r1', 'city': 'Austin', 'price': 1500, 'type': 'apartment'}, {'id': 'r2', 'city': 'Seattle', 'price': 2200, 'type': 'house'}]}, 'Indicator_Categories': {'categories': ['Economic', 'Social', 'Environmental', 'Governance']}, 'Search_by_company_name': {'results': [{'name': 'MTN Uganda', 'registration': '80020001234567'}, {'name': 'Stanbic Bank Uganda', 'registration': '80020002345678'}], 'registry': 'Uganda'}, 'auto_complete': {'suggestions': [{'term': 'bus', 'suggestions': ['business', 'business plan', 'business loan']}, {'term': 'mar', 'suggestions': ['marketing', 'market research']}]}, 'blogs_copy': {'blogs': [{'title': 'Startup Funding Guide', 'author': 'Sarah Chen', 'date': '2024-01-10'}, {'title': 'Growth Hacking 101', 'author': 'Mike Ross', 'date': '2024-01-05'}]}, '_edge_cases': {'empty_collections': [], 'sparse_records': [None], 'missing_fields': {}}},
]

# ─── CommerceTools (commerce) ──────────
TOOLLENS_CONFIGS["commerce"] = [
    {'Laptops': [{'id': 1, 'brand': 'Dell', 'model': 'XPS 15', 'price': 1499, 'cpu': 'Intel i7', 'ram': 16}, {'id': 2, 'brand': 'Lenovo', 'model': 'ThinkPad X1', 'price': 1899, 'cpu': 'Intel i9', 'ram': 32}, {'id': 3, 'brand': 'Apple', 'model': 'MacBook Pro', 'price': 2299, 'cpu': 'M2 Pro', 'ram': 16}], 'Get_Prices': [{'gpu': 'RTX 4090', 'price': 1599}, {'gpu': 'RTX 4070', 'price': 549}, {'gpu': 'RX 7900 XTX', 'price': 999}], 'Get_Products': [{'id': 101, 'name': 'Wireless Mouse', 'price': 29.99, 'stock': 50}, {'id': 102, 'name': 'USB Hub', 'price': 19.99, 'stock': 0}, {'id': 103, 'name': 'Webcam', 'price': 89.99, 'stock': 15}], 'Get_a_specific_item': {'known_ids': [101, 102, 103], 'sample_id': 101}, 'Get_all_the_shoes': [{'id': 201, 'brand': 'Nike', 'name': 'Air Max', 'size': 10, 'price': 129}, {'id': 202, 'brand': 'Adidas', 'name': 'Ultraboost', 'size': 9, 'price': 180}, {'id': 203, 'brand': 'Puma', 'name': 'Suede', 'size': 11, 'price': 65}], 'Search_Product': {'query': 'laptop', 'expected_results': ['Dell XPS 15', 'MacBook Pro']}, 'Search_Products': {'country': 'US', 'query': 'headphones', 'last_page': 5}, 'Search_for_Creators': {'search_query': 'tech review', 'sample_creators': ['Marques Brownlee', 'Linus Tech Tips']}, 'Search_on_ebay': {'query': 'vintage camera', 'country': 'US'}, 'getProducts': [{'id': 301, 'name': 'Coffee Maker', 'price': 49.99}, {'id': 302, 'name': 'Blender', 'price': 79.99}], 'mailcheck': {'test_emails': ['user@gmail.com', 'test@tempmail.com', 'admin@company.org']}, 'newlyRegisteredDomains': {'sample_domains': ['example.com', 'mynewsite.org', 'testdomain.net'], 'days_back': 7}, 'sortProductsMaster': {'available_sorts': ['price_asc', 'price_desc', 'name_asc', 'name_desc', 'newest', 'popularity']}, 'empty_collections': {'Get_Products_empty': [], 'Laptops_sparse': []}},
]

# ─── EducationTools (education) ──────────
TOOLLENS_CONFIGS["education"] = [
    {'random_treasures': [{'id': 't1', 'name': 'Gold Coin', 'value': 500}, {'id': 't2', 'name': 'Silver Chalice', 'value': 300}], 'topics': {'math': [{'title': 'Algebra Basics', 'content': 'Linear equations and variables'}], 'science': [{'title': 'Photosynthesis', 'content': 'Process of converting light to energy'}], 'history': [{'title': 'World War II', 'content': '1939-1945 global conflict'}]}, 'ai_questions': [{'q': 'What is gravity?', 'a': 'Force attracting objects with mass'}], 'names': ['Alice', 'Bob', 'Charlie'], 'chemical_elements': [{'symbol': 'H', 'name': 'Hydrogen', 'number': 1}, {'symbol': 'O', 'name': 'Oxygen', 'number': 8}, {'symbol': 'Au', 'name': 'Gold', 'number': 79}], 'physical_constants': [{'name': 'Speed of Light', 'value': '299792458', 'unit': 'm/s'}, {'name': 'Planck Constant', 'value': '6.626e-34', 'unit': 'J*s'}], 'space_news': [{'title': 'Mars Rover Discovery', 'date': '2024-01-15', 'summary': 'New evidence of water'}], 'random_words': ['serendipity', 'ephemeral', 'quintessential'], 'date_facts': {'01-15': 'Martin Luther King Jr. born in 1929', '07-04': 'US Declaration of Independence adopted in 1776'}, 'equations': [{'name': "Einstein's Mass-Energy", 'formula': 'E=mc^2'}, {'name': "Newton's Second Law", 'formula': 'F=ma'}], 'numbers_translations': {'42': 'forty-two', '100': 'one hundred'}, 'planets': [{'name': 'Mercury', 'star': 'Sun'}, {'name': 'Venus', 'star': 'Sun'}, {'name': 'Earth', 'star': 'Sun'}], 'quiz_today': [{'question': 'Capital of France?', 'answer': 'Paris'}], 'recent_words_dc': [{'word': 'petrichor', 'definition': 'Earthy scent after rain'}], 'word_of_day_ld': {'word': 'ubiquitous', 'definition': 'Present everywhere'}, 'word_of_day_mw': {'word': 'candid', 'definition': 'Honest, frank'}, 'word_of_day_pm': {'word': 'nostalgia', 'definition': 'Sentimental longing'}, 'dashboard': {'stats': {'users': 1250, 'courses': 45}}, 'questions_answers': [{'type': 'multiple_choice', 'question': '2+2?', 'answer': '4', 'feedback': 'Basic addition'}], 'periodic_table': [{'element': 'Carbon', 'symbol': 'C', 'mass': 12.011}], 'quotes': [{'text': 'Knowledge is power', 'author': 'Francis Bacon'}], 'turkish_words': [{'word': 'kitap', 'meaning': 'book'}, {'word': 'su', 'meaning': 'water'}], 'empty_collections': [], 'sparse_data': {}},
]

# ─── EmailTools (email) ──────────
TOOLLENS_CONFIGS["email"] = [
    {'Current_Mail': {'valid_emails': ['john.doe@gmail.com', 'jane.smith@yahoo.com', 'bob.jones@outlook.com'], 'invalid_emails': ['not.an.email', 'missing@domain', '@nodomain.com', 'plain text'], 'mixed_list': ['valid.user@hotmail.com', 'invalid@@mail.com', 'good@bad..com', 'another.valid@proton.me']}, 'Email': {'test_addresses': ['alice@company.org', 'bob@', 'charlie@.com', 'valid123@sub.domain.co.uk', 'user@name with space.com', 'test@domain.info']}, 'Email_verifier': {'emails_to_verify': ['contact@business.net', 'admin@gov.edu', 'fake@nonexistent-domain-xyz123.com', 'test@10minutemail.com', 'user@mailinator.com']}, 'EmailVerifications': {'batch_valid': ['team@startup.io', 'support@techcorp.com', 'info@nonprofit.org'], 'batch_invalid': ['bad@', '@missing.com', 'no.at.symbol', 'double@@at.com'], 'batch_mixed': ['real@company.com', 'fake@nonexistent.xyz', 'good@email.org', '@bad.com', 'valid@domain.co']}, 'FreeDomain': {'free_domains': ['gmail.com', 'yahoo.com', 'hotmail.com', 'outlook.com', 'protonmail.com', 'mail.com'], 'paid_domains': ['company.org', 'business.net', 'startup.io', 'techcorp.com', 'enterprise.co.uk'], 'unknown_domains': ['randomtest1234.com', 'fakedomain99999.net']}, 'Validate_domain_or_email_address': {'domains': ['spam4.me', 'example.com', 'sub.domain.org', 'invalid..dots.com', 'no-tld'], 'email_addresses': ['badactor@spam4.me', 'user@example.com', 'test@sub.domain.org', '@nodomain.com', 'user@.com'], 'mixed_inputs': ['valid@email.com', 'just-a-domain.com', '@', 'user@', 'domain.org']}, 'Verify_Email': {'deliverable': ['contact@amazon.com', 'support@microsoft.com', 'team@google.com'], 'undeliverable': ['bounce@nonexistent-domain-12345.com', 'fake@deleted-domain-67890.net', 'invalid@no-mx-record.xyz'], 'risky': ['temp@10minutemail.com', 'disposable@mailinator.com', 'throwaway@guerrillamail.com']}, 'mailCheck': {'valid_patterns': ['alice@gmail.com', 'bob123@yahoo.com', 'charlie.brown@hotmail.com', 'd_morgan@outlook.com'], 'invalid_patterns': ['1invalid@gmail.com', '.startswithdot@yahoo.com', '-hyphen@hotmail.com', '_underscore@outlook.com', 'user@domain', 'user@.com', 'user@domain..com'], 'edge_cases': ['a@b.co', 'valid.user+tag@gmail.com', 'user@subdomain.domain.co.uk', 'UPPERCASE@DOMAIN.COM', 'user@123.456.789.012']}},
]

# ─── WeatherTools (weather) ──────────
TOOLLENS_CONFIGS["weather"] = [
    {'api_key': 'YOUR_API_KEY', 'stations': [{'id': '9414290', 'name': 'San Francisco'}, {'id': '9410170', 'name': 'Los Angeles'}], 'countries': ['US', 'CA', 'GB', 'AU'], 'resorts': ['Aspen', 'Whistler', 'Stowe', 'Park City'], 'earthquakes': [{'id': 'us7000abc', 'place': 'California'}, {'id': 'us7000def', 'place': 'Alaska'}], 'locations': [{'lat': 40.7128, 'lon': -74.006, 'city': 'New York'}, {'lat': 34.0522, 'lon': -118.2437, 'city': 'Los Angeles'}], 'zip_codes': ['10001', '90210', '94102'], 'climate_key': 'ABCD1234', 'forecasts': {}, 'alerts': []},
]

# ─── MusicTools (music) ──────────
TOOLLENS_CONFIGS["music"] = [
    {'videos': {'youtube_24h': ['dQw4w9WgXcQ', '3tmd-ClpJxA'], 'youtube_trending_overall': ['9bZkp7q19f0'], 'youtube_weekly': []}, 'charts': {'Artist_100': [{'rank': 1, 'artist': 'Taylor Swift', 'weeks': 10}], 'BILLBOARD_200': [{'rank': 1, 'album': 'Midnights', 'artist': 'Taylor Swift', 'last_week': 1}], 'Billboard_200': [{'rank': 1, 'album': 'Midnights', 'artist': 'Taylor Swift'}], 'Billboard_Global_Excl_US': [], 'Billboard_Hot_100': [{'rank': 1, 'song': 'Anti-Hero', 'artist': 'Taylor Swift'}], 'Catalog_Albums': [{'rank': 1, 'album': 'Thriller', 'artist': 'Michael Jackson'}], 'Greatest_of_All_Time_Hot_100_Songs': [{'rank': 1, 'song': 'Blinding Lights', 'artist': 'The Weeknd'}], 'Independent_Albums': [{'rank': 1, 'album': 'RTJ4', 'artist': 'Run The Jewels'}], 'Year_End_Billboard_Global_200': [{'rank': 1, 'song': 'Heat Waves', 'artist': 'Glass Animals'}], 'Year_End_Top_Artists': [{'rank': 1, 'artist': 'Taylor Swift'}]}, 'users': {'spotify_user_1': {'display_name': 'John Doe', 'id': 'spotify_user_1', 'followers': 100}, 'unknown_user': {}}, 'albums': {'List_User_Albums': {'spotify_user_1': ['album1', 'album2'], 'empty_user': []}, 'New_releases': {'US': [{'album': 'Album1', 'artist': 'Artist1'}], 'GB': []}}, 'search': {'auto_complete': {'hello': ['hello world', 'hello goodbye'], 'empty': []}, 'boy_groups': ['BTS', 'EXO'], 'girl_groups': ['BLACKPINK', 'TWICE'], 'random_boy_group': 'BTS', 'random_song': {'artist': 'Taylor Swift', 'album': '1989', 'song': 'Shake It Off'}}, 'channels': ['channel1', 'channel2']},
]

# ─── VideoImagesTools (video_images) ──────────
TOOLLENS_CONFIGS["video_images"] = [
    {'available_modes': ['mask', 'blur', 'replace'], 'movies': [{'id': 1, 'title': 'The Shawshank Redemption', 'year': 1994, 'genre': 'Drama', 'rating': 9.3}, {'id': 2, 'title': 'The Godfather', 'year': 1972, 'genre': 'Crime', 'rating': 9.2}, {'id': 3, 'title': 'Inception', 'year': 2010, 'genre': 'Sci-Fi', 'rating': 8.8}, {'id': 4, 'title': 'Interstellar', 'year': 2014, 'genre': 'Sci-Fi', 'rating': 8.6}, {'id': 5, 'title': 'Parasite', 'year': 2019, 'genre': 'Thriller', 'rating': 8.6}], 'empty_genre': [], 'single_movie': [{'id': 6, 'title': 'Test Movie', 'year': 2023, 'genre': 'Comedy', 'rating': 7.0}], 'genres': ['Drama', 'Crime', 'Sci-Fi', 'Thriller', 'Comedy', 'Action'], 'sort_options': ['title', 'year', 'rating'], 'default_sort': 'year'},
]
